[package]
name = "photopack-cli"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "photopack"
path = "src/main.rs"

[dependencies]
photopack-core = { path = "../core" }
clap = { version = "4", features = ["derive"] }
anyhow = "1"
indicatif = "0.17"
chrono = "0.4"
comfy-table = "7"
